///////////////////////////////////////////////////////////////
//
//  EE 2073
//
//  Homework 2
//
//  I certify that the code below is my own work without AI assistance.
//  Korbin Davis xya241
//
// Variables:
// Ra: Value of Resistor A in the RC circuit (resistance)
// Rb: Value of Resistor B in the RC circuit (resistance)
//  C: Value of Capacitor C in the RC circuit (capacitance)

#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif // _CRT_SECURE_NO_WARNINGS

#include <stdio.h>
#include <math.h>

// Calculate the frequency of the square wave generated by the 555 timer
// based on the values of the resistors and capacitor
double frequency(double Ra, double Rb, double C) {
    // f = 1/T = 1.44/(C*(Ra+2*Rb))
    return 1.44 / (C * (Ra + 2 * Rb));
}

// Calculate the Duty Cycle of the 555 timer based on the values of the resistors
double dutyCycle(double Ra, double Rb) {
    // D = Rb/(Ra+2*Rb)
    return Rb/(Ra + 2 * Rb);
}

// Test the functions created to model the 555 timer chip 
int main(void) {
    double freq;
    double dutyC;

    double Ra = 4.7e3;
    double Rb = 10e3;
    double  C = 1e-6;

    // Test each function above
    freq  = frequency(Ra, Rb, C);
    dutyC = dutyCycle(Ra, Rb);
    
    printf("Ra = %.1e\tRb = %.1e\tC = %.1e\tfrequency = %.1f\tduty cycle = %.2f\n", Ra, Rb, C, freq, dutyC);

    // Test again with new values. Don't declare the variables twice.
    Ra = 10;
    Rb = 100;
     C = 1e-5;

    freq  = frequency(Ra, Rb, C);
    dutyC = dutyCycle(Ra, Rb);

    printf("Ra = %.1e\tRb = %.1e\tC = %.1e\tfrequency = %.1f\tduty cycle = %.2f\n", Ra, Rb, C, freq, dutyC);

    return 0;
}
